### ISSUE TITLE
Set up plugin

### ISSUE THREAD

**Issue by libpoet1312** [samngms/kong-plugin-dynamic-route#1]
Hello!

I am a newbie in kong and I would like to setup this plugin for this logic:
If the request have a query param I need to redirect traffic to another host.

The curl I run is:

`{
    "route": { "id": "80628c4e-63ae-4b97-96c3-bd3277695828"},
    "service": null,
    "protocols": ["http", "https"],
    "enabled": false,
    "config": {
        "debug": true,
        "exact_match": {
                "conditions":"$query.name",
                "values":"test",
                "dynamic_host":"ANOTHER HOST"
        }
    },
    "name": "dynamic-route"
}`

I get an error saying that `"exact_match": "expected a map"`. What kind of data structure must I provide the admin endpoint in order to pass the config?

**Comment by samngms** [comment]
Please try the following

```
{ "route": 
    {"id": "80628c4e-63ae-4b97-96c3-bd3277695828"}, 
    "service": null, 
    "protocols": ["http", "https"], 
    "enabled": false, 
    "config": { 
        "debug": true, 
        "exact_match": { 
            "your_original_path_here": {
                "GET|POST|*": [
                    {
                        "condition": "${query.name}",
                        "values": ["test"],
                        "dynamic_host": "foobar.com",
                        "dynamic_port": 443
                    }
                ]                
            }
        } 
    }, 
    "name": "dynamic-route" 
}
```

`Exact match` means the URL match exactly this path. Sorry for the ugly field name.

**Comment by libpoet1312** [comment]
thank you very much!
